name: 'MSVC 2019'

on:
  push:
    branches: master

jobs:
  build:
    name: 'build MSVC 2019'
    runs-on: ubuntu-latest
    steps:
      - name: "complie src"
        run: |
          echo "set environment"
          ls > echo
          ls .. > echo
          ls .... > echo
          g++ --version
          g++ ../main.cpp -o main
          ./main
