name: 'MSVC 2019'

on: push

jobs:
  build:
    name: 'build MSVC 2019'
    runs-on: ubuntu-latest
    steps:
      - name: "complie src"
        run: |
          echo "set environment"
          echo $(get-location)
          cmake ../
          make
          ./githubAction-release
