name: 'MSVC 2019'

on:
  push:
    branches: master

jobs:
  build:
    name: 'build MSVC 2019'
    runs-on: windows-latest
    steps:
      - name: "complie src"
        run: 
          echo "set environment";
          cmake .
          make
          ./githubAction-release
          # g++ ./main.cpp -o ./main.exe; ./main.exe;
