name: 'MSVC 2019'

on: push

jobs:
  build:
    name: 'build MSVC 2019'
    runs-on: ubuntu-latest
    steps:
      - name: "获取源码"
        uses: actions/Checkout@master
        
      - name: "complie src"
        run: |
          echo "set environment"
          g++ *.cpp -o main
          ./main
